---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ansi-key"
      instance_type: t2.micro
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0d0f28110d16ee7d6", name: "amazon-node-1" } # Update AMI ID according 
      - { image: "ami-0cb91c7de36eed2cb", name: "ubuntu-node-2" } # to your account
      - { image: "ami-0cb91c7de36eed2cb", name: "ubuntu-node-3" }
